{% set version = "3.7" %}

package:
    name: simbody
    version: {{ version }}

source:
    fn: Simbody-{{ version }}.tar.gz
    url: https://github.com/simbody/simbody/archive/Simbody-{{ version }}.tar.gz
    sha256: d371a92d440991400cb8e8e2473277a75307abb916e5aabc14194bea841b804a
    patches:
      - 716.patch

build:
    number: 2
    run_exports:
        - {{ pin_subpackage('simbody', max_pin='x.x') }}
    # NOTE : This is needed to ensure the paths to Simbody's binaries, like
    # simbody-visualizer, are corrected.
    detect_binary_files_with_prefix: true

# NOTE: This installs Simbody and the optional visualizer on Linux, Windows,
# and OSX. On Windows, we build against the openblas available in conda-forge,
# which includes lapack, because the other blas/lapack packages do not provide
# import libraries (*.lib). We only depend on Glut on Linux, because Glut is
# included with Simbody for Windows and OSX includes a Glut implementation.
# https://github.com/AnacondaRecipes/r-rgl-feedstock/blob/master/recipe/meta.yaml#L48-L67
requirements:
    build:
        # CMake 3.8 provides imported targets for OpenGL.
        - cmake >=3.8
        - ninja  # [win]
        - doxygen
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxcomposite-devel') }}   # [linux]
        - {{ cdt('libxcursor-devel') }}      # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - {{ cdt('libxrandr-devel') }}       # [linux]
        - {{ cdt('libxscrnsaver-devel') }}   # [linux]
        - {{ cdt('libxtst-devel') }}         # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libsm-devel') }}           # [linux]
        - {{ cdt('libice-devel') }}          # [linux]
        - {{ cdt('libxt') }}                 # [linux]
        - {{ cdt('libxt-devel') }}           # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxau') }}                # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('expat') }}                 # [linux]
    host:
        - openblas  # [win]
        - libblas  # [not win]
        - liblapack  # [not win]
        - libglu  # [linux]
        - freeglut  # [linux]
        - xorg-libxmu  # [linux]
    run:
        - openblas  # [win]
        - libglu  # [linux]
        - freeglut  # [linux]
        
test:
  commands:
    - test -f $PREFIX/libexec/simbody/simbody-visualizer              # [linux]
    - test -f $PREFIX/libexec/simbody/simbody-visualizer.app/Contents/MacOS/simbody-visualizer  # [osx]
    - if not exist %LIBRARY_BIN%\\simbody-visualizer.exe exit 1       # [win]
    - test -f $PREFIX/include/simbody/Simbody.h                       # [unix]
    - test -f $PREFIX/include/simbody/SimTKcommon.h                   # [unix]
    - test -f $PREFIX/include/simbody/SimTKlapack.h                   # [unix]
    - test -f $PREFIX/include/simbody/SimTKmath.h                     # [unix]
    - test -f $PREFIX/include/simbody/SimTKsimbody_aux.h              # [unix]
    - test -f $PREFIX/include/simbody/SimTKsimbody.h                  # [unix]
    - if not exist %LIBRARY_INC%\\Simbody.h exit 1                    # [win]
    - if not exist %LIBRARY_INC%\\SimTKcommon.h exit 1                # [win]
    - if not exist %LIBRARY_INC%\\SimTKlapack.h exit 1                # [win]
    - if not exist %LIBRARY_INC%\\SimTKmath.h exit 1                  # [win]
    - if not exist %LIBRARY_INC%\\SimTKsimbody_aux.h exit 1           # [win]
    - if not exist %LIBRARY_INC%\\SimTKsimbody.h exit 1               # [win]
    - test -f $PREFIX/lib/libSimTKcommon.so                           # [linux]
    - test -f $PREFIX/lib/libSimTKmath.so                             # [linux]
    - test -f $PREFIX/lib/libSimTKsimbody.so                          # [linux]
    - test -f $PREFIX/lib/libSimTKcommon.dylib                        # [osx]
    - test -f $PREFIX/lib/libSimTKmath.dylib                          # [osx]
    - test -f $PREFIX/lib/libSimTKsimbody.dylib                       # [osx]
    - if not exist %LIBRARY_BIN%\\SimTKcommon.dll exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\SimTKmath.dll exit 1                # [win]
    - if not exist %LIBRARY_BIN%\\SimTKsimbody.dll exit 1             # [win]
    # Regression test for https://github.com/conda-forge/simbody-feedstock/issues/39
    - if exist %LIBRARY_INC%\\dirent.h exit 1                    # [win]
  files:
    - test
  requires:
    - cmake >=3.8
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
    home: https://simtk.org/home/simbody
    license: Apache-2.0
    license_file: LICENSE.txt
    dev_url: https://github.com/simbody/simbody
    doc_url: https://simbody.github.io
    summary: >
        High-performance C++ multibody dynamics/physics library for simulating
        articulated biomechanical and mechanical systems like vehicles, robots,
        and the human skeleton.

extra:
    recipe-maintainers:
        - moorepants
        - chrisdembia
