compiler_stack: comp7
conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
provider: {linux_aarch64: default}
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
